site_name: Association "High Altitude Lab"
site_description: >-
copyright: >-
  Copyright &copy; 2026 - Association "High Altitude Lab" and all contributors.
  The content and the license are licensed under CC BY 4.0
repo_url: https://github.com/highaltitudelab/website
repo_name: GitHub Repo
edit_uri: edit/main/
site_url: https://highaltitudelab.com

# Build
site_dir: _site
docs_dir: .

nav:
  - Governance:
    - Association Charter: governance/association/charter.md
  - Resources:
    - Privacy Policy: governance/policies/1_privacy-policy.md

plugins:
  - search
  - autorefs
  - macros
  - mkdocs-pdf
  - same-dir

# Markdown
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: '#'
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - mdx_truly_sane_lists

# Theme
theme:
  name: material
  custom_dir: overrides
  highlightjs: true
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.path
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  font:
    text: DM Sans
    code: Roboto Mono
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  favicon: assets/images/logo/logo.svg
  logo: assets/images/logo/logo.png
  icon:
    repo: fontawesome/brands/github

extra_css:
  - assets/css/theme.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/highaltitudelab
      name: GitHub
